### ISSUE TITLE
fresh start fails from instructions in the README page

### ISSUE THREAD

**Issue by daviortega** [biowonks/projects#9]
```bash
$bin/setup-docker-dev.sh 
biowonks-dev uses an image, skipping
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

**Comment by daviortega** [comment]
I read somewhere that defining `DOCKER_HOST` to `127.0.0.1` would solve the problem. It didn't:

```bash
 $ export DOCKER_HOST=127.0.0.1
 $ bin/setup-docker-dev.sh 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.14.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib64/python3.4/site-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib64/python3.4/site-packages/compose/cli/main.py", line 115, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib64/python3.4/site-packages/compose/cli/command.py", line 37, in project_from_options
    override_dir=options.get('--project-directory'),
  File "/usr/lib64/python3.4/site-packages/compose/cli/command.py", line 99, in get_project
    host=host, environment=environment
  File "/usr/lib64/python3.4/site-packages/compose/cli/command.py", line 71, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/usr/lib64/python3.4/site-packages/compose/cli/docker_client.py", line 95, in docker_client
    return APIClient(**kwargs)
  File "/usr/lib64/python3.4/site-packages/docker/api/client.py", line 109, in __init__
    base_url, IS_WINDOWS_PLATFORM, tls=bool(tls)
  File "/usr/lib64/python3.4/site-packages/docker/utils/utils.py", line 373, in parse_host
    "Bind address needs a port: {0}".format(addr))
docker.errors.DockerException: Bind address needs a port: 127.0.0.1
 ```

**Comment by daviortega** [comment]
It does not seem to be an issue from MiST... I think my docker installation is not working.
